color: red
fieldLayouts:
  c6176515-5220-4592-b66b-b097a89ae430:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:01:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 384be35b-4e2b-417b-90b3-1243967922d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:03:01+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e5ea7be-9f59-463d-b915-09dc7bd9875f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:03:01+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4047442c-38dd-4437-ba93-1766c845151f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d138fc4-9e31-44f6-b49d-32af054c492d
        userCondition: null
handle: categories
hasTitleField: true
icon: grid-2
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
