color: yellow
fieldLayouts:
  9c4c5fb0-8e4f-4e00-931c-78079b1693e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T11:16:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b72567a9-7e05-477b-9a71-0917177736e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T11:19:44+00:00'
            elementCondition: null
            fieldUid: 5f6f6bc1-d5b3-4a8a-b4de-7bb5feb71a34 # Page Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09775a15-0d50-4770-bad0-cb185383db78
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40edd221-5267-4772-a109-2b1b11d11347
        userCondition: null
handle: navigation
hasTitleField: true
icon: bars
name: Navigation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
