columnSuffix: null
handle: city
instructions: null
name: City
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:62df7f55-9032-4da0-82c5-36ee0f68af64' # Locations
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
