dateModified: 1732274620
email:
  fromEmail: voornaam.naam@howest.be
  fromName: 'Craft Template'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/local'
    type: craft\fs\Local
    url: '@web/local'
meta:
  __names__:
    5d45f9f4-7ab7-4459-926d-a8006cad4227: Images # Images
    5f6f6bc1-d5b3-4a8a-b4de-7bb5feb71a34: 'Page Link' # Page Link
    6bbd9daa-bd0e-47a7-a80f-00486e954c31: City # City
    10d2260b-dd05-4a49-abb3-800017e15928: 'Craft Template' # Craft Template
    21d6f9ae-1d22-490e-bd89-d6ded5d514ac: 'body text' # body text
    30fd9242-d15e-4445-8d18-59ccad07280d: Categories # Categories
    35c35080-108d-485f-925f-407a5ab65a22: Cover # Cover
    62df7f55-9032-4da0-82c5-36ee0f68af64: Locations # Locations
    955b3b78-0dbd-47ac-9db5-c15151bf0b94: Details # Details
    1094b8b3-5e0b-4264-b997-5e1e4110a127: House # House
    3519abcb-b5dc-4fac-b04a-b3451f8ba36a: Categories # Categories
    19178fcc-602e-4e2e-a2a4-abf44f2ec6a3: House # House
    98922ece-f9a2-48c7-aca3-dcdd1c2a0c7a: Locations # Locations
    1765228e-0ad3-49c0-a7df-f552ada1e942: State # State
    a090dd73-2425-4aa0-8d69-c4a79a1bb99d: Navigation # Navigation
    a3917b41-5b9e-455d-82b1-9867d010e228: 'Body Text' # Body Text
    aafc78a0-aaf5-42e3-b98e-8c985c9691ab: Carousel # Carousel
    bb176edb-885d-48f2-96e4-9714b8af2c55: Navigation # Navigation
    bfc5caff-33ac-495a-8336-7abe2887b021: 'Public Schema' # Public Schema
    d3b42bd7-e7fb-4536-8773-1f5957362b49: Price # Price
    da3960aa-bd94-4084-bc03-80601465ba16: Category # Category
    e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8: 'Plain Text' # Plain Text
    e40d6760-127c-4b8a-a227-7148c8e9991b: Strengths # Strengths
    f6eaef1f-2f88-4856-8eee-c5ae9620f572: 'Craft Template' # Craft Template
    fcf193b7-cca5-41f7-a307-b68aca4a559c: 'List Item' # List Item
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  mapbox:
    edition: standard
    enabled: true
    licenseKey: 74YGDDBK0VJ54KD9VCZ0MFNC
    schemaVersion: 1.1.0
    settings:
      accessToken: null
      enableJsLogging: true
      minifyJsFiles: false
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Template'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
