defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3519abcb-b5dc-4fac-b04a-b3451f8ba36a # Categories
handle: categories
maxAuthors: 1
name: Categories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: categories/_entry.twig
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: eb20fac8-6546-4f51-ba9f-69072981a2e1
type: structure
